INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (1, 'Tonghae');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (2, 'Emmen');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (3, 'Dalang');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (4, 'Asadābād');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (5, 'Smętowo Graniczne');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (6, 'Lubao');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (7, 'Lobanovo');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (8, 'Halmstad');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (9, 'Newark');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (10, 'Vokhaïkó');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (11, 'Maicao');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (12, 'Horten');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (13, 'Pyshchug');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (14, 'Marte');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (15, 'Longmen');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (16, 'Bella Vista');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (17, 'Jiulong');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (18, 'Vitarte');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (19, 'Balas');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (20, 'Aradac');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (21, 'Humaitá');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (22, 'Paris 19');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (23, 'Pallisa');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (24, 'Liyang');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (25, 'Zheleznovodsk');

INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (26, 'Heicheng');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (27, 'Saguenay');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (28, 'San Marcos');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (29, 'Pont-Audemer');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (30, 'Strelitsa');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (31, 'Simpang');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (32, 'Varennes');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (33, 'Sulo');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (34, 'Bolkhov');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (35, 'Aḑ Ḑil‘');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (36, 'Matara');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (37, 'Drammen');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (38, 'Přibyslav');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (39, 'Gadon');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (40, 'Lugang');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (41, 'Sibulan');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (42, 'Deqing');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (43, 'Cikeper');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (44, 'Tulay na Lupa');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (45, 'Puutura');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (46, 'Sicamous');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (47, 'Da’anshan');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (48, 'Sairam');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (49, 'Mawlamyinegyunn');

INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (50, 'Muzidian');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (51, 'Cherbourg-Octeville');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (52, 'Ijero-Ekiti');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (53, 'Abovyan');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (54, 'Yuelai');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (55, 'Shal’skiy');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (56, 'Shaxi');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (57, 'Auray');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (58, 'Oslo');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (59, 'Beiquan');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (60, 'Birnin Kebbi');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (61, 'Guanzhuang');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (62, 'Nakanojōmachi');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (63, 'La Rochelle');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (64, 'Fengle');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (65, 'Göteborg');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (66, 'Yarabamba');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (67, 'Al Mazār');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (68, 'Puma');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (69, 'Huanggu');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (70, 'Sovetsk');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (71, 'Carangola');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (72, 'San Juan');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (73, 'Bum Bum');

INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (74, 'Joutseno');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (75, 'Dera Murād Jamāli');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (76, 'Xiaoyan');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (77, 'Al Mughayyir');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (78, 'Higetegera');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (79, 'Minami-rinkan');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (80, 'Labuan');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (81, 'Singapore');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (82, 'Araguaína');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (83, 'Västervik');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (84, 'Libertad');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (85, 'Kičevo');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (86, 'Kostyantynivka');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (87, 'Gielniów');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (88, 'Arjawinangun');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (89, 'El Potrero');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (90, 'Xiaotao');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (91, 'Saue');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (92, 'Catujal');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (93, 'Dianzi');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (94, 'Mucumpiz');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (95, 'Yeri');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (96, 'Vidual');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (97, 'Iwade');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (98, 'Debrecen');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (99, 'Qiandong');
INSERT INTO PROVINCIA (Codigo_Provincia, Nombre) values (100, 'Fontainebleau');
